### ISSUE TITLE
Add image based on JDK

### ISSUE THREAD

**Issue by EnmanuelReyes** [timbru31/docker-java-node#414]
It would be good to have an image based on a JDK instead of the JRE.

Anyone who has projects that have NPM and Java under the same umbrella could use it!

I can do a PR if you want!

**Comment by timbru31** [comment]
Yeah for our use case a JRE was enough (and way smaller) than using a JDK, but to support a JDK variant, too, would be nice.

So PR's welcome! :)

**Comment by timbru31** [comment]
I've added JDK flavors to this repo. Docker build will probably take around 1-2 hours to build (their infrastructure is very slow)
