### ISSUE TITLE
Yarn is not found

### ISSUE THREAD

**Issue by CaptainChemist** [timbru31/docker-java-node#47]
When I use this docker image in the .gitlab-ci.yml, I get an error that yarn cannot be found even though it can find npm. Before running a yarn command I do an `apt-get update -qq && apt-get install` and that also doesn't make yarn appear.  Is there a path exporting I need to do first?

Thanks for the great package!

**Comment by timbru31** [comment]
Thanks, I'll take a look what's wrong.
