### ISSUE TITLE
standard_init_linux.go:211: exec format on Amazon EC2 arm64 machine

### ISSUE THREAD

**Issue by donmezburak** [timbru31/docker-java-node#518]
Hello ,

I am using docker in Amazon EC2 machine. Machine info is:

AMI ID
ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-arm64-server

My Dockerfile is:

FROM timbru31/java-node:latest
WORKDIR /app
COPY . .
RUN npm install && npm install -g @angular/cli
EXPOSE ${FM_PORT}
ENTRYPOINT ["node", "--inspect=0.0.0.0:9227", "fmApiStart.js"]

I am getting error like:

Building fm
Step 1/6 : FROM timbru31/java-node:latest
 ---> d6ffef8c831a
Step 2/6 : WORKDIR /app
 ---> Running in 14f876ed607f
Removing intermediate container 14f876ed607f
 ---> 8bb17e94124f
Step 3/6 : COPY . .
 ---> 30e4f36678f0
Step 4/6 : RUN npm install && npm install -g @angular/cli
 ---> Running in 612d3b2f7e7f
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'fm' failed to build: The command '/bin/bash -o pipefail -c npm install && npm install -g @angular/cli' returned a non-zero code: 1

How can I handle this ?

Thanks

**Comment by timbru31** [comment]
It seems that inside the container `npm install && npm install -g @angular/cli` fails. Could you share your `package.json` file?

**Comment by donmezburak** [comment]
I changed image to alpine ubuntu and installed node and command works. This is the content of package.json:

> {
  "name": "robotic-file-manager",
  "version": "1.0.0",
  "description": "File manager api for robotic",
  "scripts": {
    "start": "node fmApiStart.js -e prod",
    "debug": "nodemon --inspect-brk=0.0.0.0:9229 fmApiStart.js"
  },
  "dependencies": {
    "adm-zip": "^0.4.7",
    "appium-support": "^2.38.1",
    "aws-sdk": "^2.540.0",
    "bluebird": "*",
    "express": "*",
    "fs-extra": "9.0.0",
    "fstream": "^1.0.12",
    "gherkin": "^4.0.0",
    "minimist": "*",
    "mkdirp": "^0.5.1",
    "multiparty": "^4.1.2",
    "rimraf": "*",
    "streamifier": "*",
    "unzipper": "^0.10.10",
    "uuid": "^3.1.0",
    "xml2js": "^0.4.17"
  },
  "homepage": "http://dev.mobinavel.com:8080/tfs/RoboticMobi/RoboticNode",
  "private": true
}

**Comment by timbru31** [comment]
The npm commands work fine when pulling and running `timbru31/java-node:latest`. Is it possible for you to share the `fmApiStart.js` file, too? I suspect it's either missing the +x flag or a valid hash bang.

**Comment by donmezburak** [comment]
yes sure. As I said, it works normally on my local machine (macOS). I thought that problem is about architecture type Amazon EC2 (arm64). 

[fmApiStart.js.zip](https://github.com/timbru31/docker-java-node/files/4739946/fmApiStart.js.zip)


All of codes are related to api rest calling (express).

**Comment by timbru31** [comment]
Thanks, I'll debug further.

**Comment by timbru31** [comment]
Alright, I've launched AMI (ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-arm64-server-20200311 (ami-00523c5e5a67c3b52)) (which results in `Linux ip-172-31-35-86 4.15.0-1060-aws #62-Ubuntu SMP Tue Feb 11 21:24:49 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`) installed Docker from the official repo (https://docs.docker.com/engine/install/ubuntu/) and can confirm the bug.

Upon investigation, it seems the underlying `openjdk` docker images are broken (or at least something changed):

![Anmerkung 2020-06-06 165307](https://user-images.githubusercontent.com/838003/83947252-73d71600-a805-11ea-8d91-12d2ca6f148f.jpg)

My Dockerfile uses SHA256 pinning and currently is at `68d29d2a9ee17a15d288368d2031bc9ffe40cbf85a92e1420696003e46a55262 (which seems the latest https://hub.docker.com/layers/openjdk/library/openjdk/11-jre/images/sha256-68d29d2a9ee17a15d288368d2031bc9ffe40cbf85a92e1420696003e46a55262?context=explore)

As you can see in the screenshot, the default pull of `openjdk:11-jre` resulted in hash `edc814766c213c163613e95935ffc95b6c3f7cee8bd339a7826feb7a33430c02` 

---

I'll have to admit that all my images are currently build for amd64, I'll look into building other architectures, too. Hopefully this will solve the issue. I'll post again once I know more.

**Comment by timbru31** [comment]
This has been fixed! I'm now providing more architectures :)
Unforunately, I've had to remove the slim flavor and switch to AdoptOpenJDK from OpenJDK - OpenJDK offers only amd64 support for Java 8.

```sh
ubuntu@ip-172-31-40-251:~$ sudo docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
timbru31/java-node   latest              542053b8caae        5 minutes ago       359MB
ubuntu@ip-172-31-40-251:~$ sudo docker run -it 542053b8caae /bin/sh
# uname -a
Linux 972603e3cd84 4.15.0-1060-aws #62-Ubuntu SMP Tue Feb 11 21:24:49 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
# java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
# node -v
v12.18.0
# ^C
#
ubuntu@ip-172-31-40-251:~$ sudo docker pull timbru31/java-node:latest
latest: Pulling from timbru31/java-node
Digest: sha256:7568589e1efb8678b372c4f9f2c4867d536f5b6a8e509180d89c9b585ab4ee95
Status: Image is up to date for timbru31/java-node:latest
docker.io/timbru31/java-node:latest
ubuntu@ip-172-31-40-251:~$ sudo docker run -it timbru31/java-node:latest@sha256:8a6448481ffdbef5a08f737152dd131f51618e80019af80d3a407062f55c431b /bin/sh
Unable to find image 'timbru31/java-node:latest@sha256:8a6448481ffdbef5a08f737152dd131f51618e80019af80d3a407062f55c431b' locally
sha256:8a6448481ffdbef5a08f737152dd131f51618e80019af80d3a407062f55c431b: Pulling from timbru31/java-node
Digest: sha256:8a6448481ffdbef5a08f737152dd131f51618e80019af80d3a407062f55c431b
Status: Downloaded newer image for timbru31/java-node@sha256:8a6448481ffdbef5a08f737152dd131f51618e80019af80d3a407062f55c431b
# ^[[A^C
#
ubuntu@ip-172-31-40-251:~$


```

**Comment by donmezburak** [comment]
Thanks man, fast response and implementation. Kudos to you. :)
