### ISSUE TITLE
Tags with alpine node 14 now use node v16 instead of node v14

### ISSUE THREAD

**Issue by thomasmattheussen** [timbru31/docker-java-node#549]
I guess due to the version of node in https://dl-cdn.alpinelinux.org/alpine/edge/main/ is now v16

**Comment by timbru31** [comment]
Yes this is correct. Will be fixed alongside #550 later today 👍

**Comment by Levino** [comment]
What is the status on this?

**Comment by timbru31** [comment]
Underlying build issues in the operating system and packages 🙁

**Comment by Levino** [comment]
So this wontfix? That is a shame. I think this is the only node/java image. Support of node 16 is quite crucial though.

**Comment by timbru31** [comment]
I won't say wontfix, but I've spent countless hours and are not that familiar with how Docker leverages multi arch behind the scenes with qemu.
If you want to debug, too, feel free to do so (any help is appreciated):
- https://github.com/docker/buildx/issues/328
- https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1928075

Hopefully Ubuntu 22.04 becomes available soonish on GH Actions so the OS bugs might be/are fixed (see https://github.com/actions/virtual-environments/issues/5428)

**Comment by Levino** [comment]
To be honest: For what I am doing this seems to be overkill. I just made my own docker image with:

```
FROM node:16
RUN apt update && apt install -y \
        default-jre
```
It is a little annoying to have to host this on a registry and update it from time to but, but whatever works, right?

Sorry to not be of more help. I hope your issues get resolved soon. Thank for your quick feed back!
