### ISSUE TITLE
Integration with pipeline

### ISSUE THREAD

**Issue by krishnastest** [timbru31/docker-java-node#572]
How can I use this in my nodejs pipeline?
I'm using allure reports with jest but allure needs java so I was looking for packages with both node and java.
Any help would be appreciated.
Thanks

**Comment by timbru31** [comment]
This depends what type of pipelines you refer to. GitHub Actions? GitLab CI? Jenkins?

**Comment by krishnastest** [comment]
Hi,
We are using bitbucket pipeline.

**Comment by timbru31** [comment]
Sadly I'm not familiar with Bitbucket and afraid I'm not much of a help. You need to look at their documentation: https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/

From skimming it, you should be able to use my provided image without any issues.
