### ISSUE TITLE
yarn GPG error, invalid signature (workaround with yarn re-install)

### ISSUE THREAD

**Issue by ArnauAregall** [timbru31/docker-java-node#586]
Hello! First of all, thank you for the provided image, I recently started using as base image for my build pipelines for a Gradle + Node personal project.

I experienced the following error without build modification:

````
Reading package lists...
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <[yarn@dan.cx](mailto:yarn@dan.cx)>
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
````

Base image I'm using is `timbru31/java-node:11-jdk-12`.

Had to re-force an install of `yarn`, although I see is already done in the [Dockerfile](https://github.com/timbru31/docker-java-node/blob/master/11/jdk/14/Dockerfile#L10-L11)

````
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list # https://github.com/yarnpkg/yarn/issues/7866
apt-get update && apt-get install -y yarn
````

Just in case you might want to review the `yarn` re-installation of the `Dockerfile`.

**Comment by ArnauAregall** [comment]
Please note I switched to `timbru31/java-node:17-jdk-14` (did the JDK upgrade also on my codebase  + Gradle 7.6) and, seems the problem is not reproducing anymore.

**Comment by timbru31** [comment]
Thanks for the issue, I'll investigate this.

**Comment by timbru31** [comment]
Worked fine for me (created a new project, used yarn add and yarn install).  
Also, Node.js 12 is EOL and thus not maintained anymore ;)
