### ISSUE TITLE
Alpine images don't respect nodejs version

### ISSUE THREAD

**Issue by mgrybyk** [timbru31/docker-java-node#597]
I want to use `timbru31/java-node:17-alpine-jre-18` which is https://github.com/timbru31/docker-java-node/blob/master/17/jre/18/alpine/Dockerfile

it installs NodeJS current which is 20 instead of 18.

Is it possible to fix the issue so that the image is built with correct version of NodeJS.

**Comment by timbru31** [comment]
Yes, I'll take a look.
