### ISSUE TITLE
Add node v20

### ISSUE THREAD

**Issue by thomasmattheussen** [timbru31/docker-java-node#609]
Node 20 started it's active LTS 24/10/2023 (https://nodejs.org/en/about/releases/)

Can we add tags for node v20 ?

**Comment by timbru31** [comment]
Yes, this will be being worked on this week 👍

**Comment by bigbang4u2** [comment]
Any update on this?

**Comment by timbru31** [comment]
Alpine is currently not ready: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/54105 so we are blocked by an upstream issue.
